---
version: '3.8'
services:
  boostcli:
    container_name: boostcli
    build: 
      context: .
      args:
        USER: ${MY_USER}
        UID: ${USER_ID}
        GID: ${GROUP_ID}
        SSH_PUBLIC_KEY: ${SSH_PUBLIC_KEY}
    image: boostcli-container
    ports:
      - "${HOST_SSH_PORT}:22"
    volumes:
      - "${MACAROON}:/lnd/readonly.macaroon:ro"
      - "${TLSCERT}:/lnd/tls.cert:ro"
      - ./userdata:/home/${MY_USER}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512m

